name: Update README

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate README content
        run: |
          REPO_NAME=$(basename $(pwd))
          REPO_DESC=$(curl -s https://api.github.com/repos/${{ github.repository }} | jq -r .description)
          echo "# $REPO_NAME" > README.md
          echo "$REPO_DESC" >> README.md

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update README with repository description"
          git push
